### ISSUE TITLE
test suite does not work properly when unittest is loaded instead of unittest2

### ISSUE THREAD

**Issue by apinio** [brandon-rhodes/python-sgp4#27]
Hi, I'm getting this output when executing `sgp4/tests.py` without unittest2 installed,

```
❯ python tests.py
EE...E..
======================================================================
ERROR: test_bad_first_line (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 135, in test_bad_first_line
    with self.assertRaisesRegex(ValueError, re.escape("""TLE format error
AttributeError: 'Tests' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: test_bad_second_line (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 147, in test_bad_second_line
    with self.assertRaisesRegex(ValueError, re.escape("""TLE format error
AttributeError: 'Tests' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: test_mismatched_lines (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 160, in test_mismatched_lines
    with self.assertRaisesRegex(ValueError, re.escape(msg)):
AttributeError: 'Tests' object has no attribute 'assertRaisesRegex'

----------------------------------------------------------------------
Ran 8 tests in 0.036s

FAILED (errors=3)
```

 However, everything is fine when test suite loads unittest2 package,

```
❯ python tests.py
........
----------------------------------------------------------------------
Ran 8 tests in 0.039s

OK
```

THX

**Comment by brandon-rhodes** [comment]
What version of Python are you using? I'm not sure the tests work with anything older than Python 2.7.

**Comment by apinio** [comment]
```
❯ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.version
2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4]
```

**Comment by brandon-rhodes** [comment]
Yes, the `tox.ini` file and the `.travis.yml` always install that library before running any tests.

But I looked, and only a small adjustment was necessary to get the tests running with stock Python 2.7+, so I've switched the tests over and only install unittest2 for Python 2.6. Let me know if the tests work for you now!

**Comment by apinio** [comment]
Test suite correctly working without unittest2 installed.

THX
